name: Arma

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Check for BOM
      uses: arma-actions/bom-check@master

  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      with:
          args: --exit w --directory '@AH-64D Apache Longbow/Addons'

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Build using HEMTT
      uses: gruppe-adler/action-release-with-hemtt@2.2.0
      with:
        cwd: '@AH-64D Apache Longbow'
